name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure Global Language Override
        run: |
          git config --global core.attributesfile "~/.gitattributes"
          echo "*.el linguist-language=Elisp" > ~/.gitattributes

      - name: Run language metrics tool
        uses: wimgoossens-dev/Github-Language-Stats@main
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "bar"
          output_path: "stats"
          use_loc: "true"
          render_legend: "true"
          dark_mode: "true"
          exclude_languages: "Astro,Markdown,Text,JSON,YAML"
           
      - name: Fix Docker Root Permissions Bug
        run: |
          sudo chown -R $USER:$USER .git
          sudo chmod -R 777 .git

      - name: Commit and push generated images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add stats/
          git commit -m "Update language statistics cake diagram" || exit 0
          git push
