name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run language metrics tool
        uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "pie"
          output_path: "stats"
          dark_mode: "true"
          git add stats/
          git commit -m "Update language statistics custom branding" || exit 0
          git push
